services:
  analytics:
    image: supabase/logflare:local
    build:
      context: ../../../..
      dockerfile: ./Dockerfile
      tags:
        - "supabase/logflare:latest"
        - "supabase/logflare:local"
